#!/bin/csh -f
set d=~/$1
mkdir $d
find . -name \*.txt -exec mv {} $d \;
find . -name wrfrst\* -exec rm -f {} \;
find . -name wrfout\* -exec rm -f {} \;
mv wrf.log $d
cp -p namelist.input $d
cp -p input_sounding $d
