#!/bin/csh -f
if ($1=="")then
set d=`git log | head -1 | sed 's/^.* //'`
set d=~/tmp/$d
else
set d=$1
endif
echo moving to $d
mkdir $d
find . -name \*.txt -exec mv {} $d \;
find . -name wrfrst\* -exec rm -f {} \;
find . -name wrfout\* -exec rm -f {} \;
mv wrf.log $d
cp -p namelist.input $d
cp -p input_sounding $d
