function [fitresult, gof] = createFit(x, y)
%CREATEFIT(x,y)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : x
%      Y Output: y
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on f06-Nov-2019 12:47:06


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( x, y );

% Set up fittype and options.
ft = 'pchipinterp';

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, 'Normalize', 'on' );


plot_fit = 0;
if plot_fit
    
    % Plot fit with data.
    figure( 'Name', 'untitled fit 1' );
    h = plot( fitresult, xData, yData );
    legend( h, 'l2 vs. short_time', 'untitled fit 1', 'Location', 'NorthEast' );
    % Label axes
    xlabel short_time
    ylabel l2
    grid on
    
end


